### ISSUE TITLE
Compare (pre-trained) YOLO algorithms

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#29]
Scoring based on accuracy & time

**Learning goal**
Figure out what the best (pre-trained) YOLO algorithms is for us to use.

**Tasks**
- [x] List of all available YOLO algorithms
- [x] Determine which algorithm to test
- [x] Compare algorithms
- [x] Pick optimal algorithm
