### ISSUE TITLE
Select data to use

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#30]
**Learning goal:**
Have a dataset prepared for our model to use.

**Tasks**
- [x] Select the datasets to use from:
 - TACO - (going to use)
 - #23
 - #24
 - #25 - (going to use)
- [x] Prepare the datasets
- [x] Merge the datasets
