### ISSUE TITLE
As a municipality, I would like to have a geographical-map with litter detections, so the cleaning service can locate litter more easily.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#37]
**Acceptance Criteria**
- Geographical-map must be able to contain markers
- The user must be able to pan across the map
- The user can zoom in/out the map
- The user can click markers, which contain litter data.

**Test case**
- [x] Test performance with 1000 markers in the Netherlands
- [x] Test performance with 100 markers per municipality

**Tasks**
- [x] Add Geographical-map
- [x] Add code to load markers

- [x] Write script to randomly generate 1000 markers in the Netherlands
- [x] Write script to randomly generate 100 markers in each municipality
