### ISSUE TITLE
As a cleaning service, I would like to be able to filter between a range of times when the litter was detected, so I can spend less time locating old and hard to find litter.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#39]
**Acceptance Criteria**
- Should show markers and/or clusters on map with corresponding time of the slider.

**Test cases**
- [x] TC01 Test detections from last 24 hours
- [x] TC02 Test detections from last 3 days
- [x] TC03 Test detections from last 1 week
- [x] TC04 Test detections from all time

**Tasks**
- [x] Add time slider control
- [x] Add time filter
