### ISSUE TITLE
As a municipality, I would want the data collected by the AI to be stored, so the cleaning services has access to it.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#49]
**Acceptance Criteria**
- Adding data must require authorization.

**Test cases** (fix this)
- [x] TC01 Check authorization 
- [x] TC02 Check error handling

**Tasks**
- [x] #51 
- [x] #64 
- [x] Set up code to call post endpoint after detections.
- [x] Set up template code
- [x] Add Prisma ORM
- [x] Set up database
- [x] Set up deployment
- [x] Add post endpoint
- [x] Secure post endpoint
- [x] Make detection component
- [x] Get and list detections in UI
