### ISSUE TITLE
Look into heatmap libraries

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#50]
**Learning goal(s)**
Goal: We want to find out if there are heatmap libraries that fit our use case.
Result: ...

**Task(s)**
- [x] Look up libraries
- [x] Test the best fitting libraries
- [x] Determine what library to use or if we should make something ourselves
