### ISSUE TITLE
Correctly format output data from Jetson

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Koen/LITR#51]
**Learning goal(s)**
Goal: We want to determine what output data is important for us, and how to get it in the correct format.
Result:
 Determine what output data is important to us:
- image frames (bitmap array)
- accuracy of model
- type of litter
- time of detection
- location
- number of detections

**Task(s)**
- [x] Determine what output data is important to us
- [x] Generate all the output data
- [x] Correctly format output data
