### ISSUE TITLE
Real time object detection (Yolov5) on Jetson Nano MVP

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Koen/LITR#64]
We test whether it is possible to run the Yolov5 model on the Jetson Nano. 

**Acceptance Criteria**
- Must test using the GPU (CUDA) of the Jetson.

**Test cases**
- [X] TC01 Test model Yolov5s
- [X] TC01 Test model Yolov5n

**Tasks**
- [X] Set up Dockerfile with correct libraries/modules
- [X] Set up real-time object detection script
- [X] Test Yolov5 models on Jetson Nano
