### ISSUE TITLE
As a cleaning service, I would like to be able to search for my municipality to help me locate it in the app faster.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#69]
**Acceptance Criteria**
- Must have an autocomplete for municipalities (in the Netherlands)
- Must pan over to the corresponding municipality

**Test cases**
- [x] TC01 Type in municipality

**Tasks**
- [x] Add search bar to the geographical-map
- [x] Add code for autocomplete for the municipalities
- [x] Add code to pan over to the corresponding municipality
