### ISSUE TITLE
As a cleaning service, I want to be able to go back to my location on the geographical-map, so I can save time finding my current location

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Koen/LITR#70]
**Acceptance Criteria**
- Go to current location on button click

**Test cases**
- [x] TC01 click on current location button

**Tasks**
- [x] Add code to go back to current based on geolocation or GPS
- [x] Add fallback code if neither work, which sends the user to the latest typed in location
