### ISSUE TITLE
As a municipality, I would like items to cluster together that are within a certain range and make them clickable to show a list, so markers stacked on top of each other are easier to excess.

### ISSUE THREAD

**Issue by Ekhorn** [FHICT-S-Koen/LITR#72]
**Acceptance Criteria**
- Markers should always be accessible by the user.

**Test cases**
- [x] TC01 click a cluster of markers
- [x] TC02 click marker
- [x] TC03 click draw bounding box

**Tasks**
- [x] install leaflet.markercluster
- [x] implement clustering
- [x] fix issues
